default_benchmark_variants:
  # NVIDIA Tesla V100 PCIe 16 GB variants
  GPU 16G: NVIDIA Tesla V100 PCIe 16 GB
  16 GB GPU: NVIDIA Tesla V100 PCIe 16 GB
  16GB GPU: NVIDIA Tesla V100 PCIe 16 GB
  V-100: NVIDIA Tesla V100 PCIe 16 GB
  V100: NVIDIA Tesla V100 PCIe 16 GB
  V100 16G: NVIDIA Tesla V100 PCIe 16 GB
  V100 16GB: NVIDIA Tesla V100 PCIe 16 GB
  V100 double precision: NVIDIA Tesla V100 PCIe 16 GB
  V100 Tesla: NVIDIA Tesla V100 PCIe 16 GB
  NVidia Volta-100: NVIDIA Tesla V100 PCIe 16 GB
  Volta GPU: NVIDIA Tesla V100 PCIe 16 GB
  Tsela V100: NVIDIA Tesla V100 PCIe 16 GB
  Tesla V10: NVIDIA Tesla V100 PCIe 16 GB

  # NVIDIA Tesla V100 PCIe 32 GB variants
  32GB gpu: NVIDIA Tesla V100 PCIe 32 GB
  Nvidia 32GB: NVIDIA Tesla V100 PCIe 32 GB
  32G GPU: NVIDIA Tesla V100 PCIe 32 GB
  Nvidia 32GB GPU: NVIDIA Tesla V100 PCIe 32 GB
  32GB GPU: NVIDIA Tesla V100 PCIe 32 GB
  GPU 32G: NVIDIA Tesla V100 PCIe 32 GB
  V100 32GB: NVIDIA Tesla V100 PCIe 32 GB
  Nvidia V100 32Go: NVIDIA Tesla V100 PCIe 32 GB
  NVIDIA Tesla 32GB: NVIDIA Tesla V100 PCIe 32 GB
  NVIDIA Volta GPU 30G: NVIDIA Tesla V100 PCIe 32 GB
  V100 32GB HBM2: NVIDIA Tesla V100 PCIe 32 GB
  Nvidia V440 32GB: NVIDIA Tesla V100 PCIe 32 GB
  NVIDIA Tesla V100 Volta 32GB: NVIDIA Tesla V100 PCIe 32 GB
  NVIDIA Tesla V100x 32GB: NVIDIA Tesla V100 PCIe 32 GB

  # NVIDIA Tesla V100 SXM2 32 GB variants
  100-SXM2-32GB: NVIDIA Tesla V100 SXM2 32 GB

  # NVIDIA Tesla V100 SXM2 16 GB variants
  NVIDIA Tesla V100 SMX2: NVIDIA Tesla V100 SXM2 16 GB

  # NVIDIA Tesla V100S PCIe 32 GB variants
  Tesla V100S-PCIE32GB: NVIDIA Tesla V100S PCIe 32 GB

  # NVIDIA DGX-2 variants
  NVIDIA DGX-2: Nvidia DGX-2
  DGX-2 GPU: Nvidia DGX-2
  DGX-2: Nvidia DGX-2

  # NVIDIA GeForce RTX 4090 variants
  RTX 24GB: NVIDIA GeForce RTX 4090
  NVIDIA GPU 24GB: NVIDIA GeForce RTX 4090
  NVIDIA 24GB GPU: NVIDIA GeForce RTX 4090
  NVIDIA 24GB: NVIDIA GeForce RTX 4090
  NVIDIA GeForce RTX 4090 24,564 MiB: NVIDIA GeForce RTX 4090
  NVIDIA RTX 24 GiB: NVIDIA GeForce RTX 4090
  NVIDIA RTX 24GB: NVIDIA GeForce RTX 4090
  24GB GPU: NVIDIA GeForce RTX 4090
  GPU 24GB: NVIDIA GeForce RTX 4090
  RTX 4090D: NVIDIA GeForce RTX 4090
  NVIDIA 4090Ti: NVIDIA GeForce RTX 4090
  RTX4090 24GB: NVIDIA GeForce RTX 4090
  NVIDIA4090: NVIDIA GeForce RTX 4090
  NVIDIA RTX 4090Ti 24GB: NVIDIA GeForce RTX 4090
  NVIDIA 4090D 24GB: NVIDIA GeForce RTX 4090
  RTX 4090 Ti: NVIDIA GeForce RTX 4090
  NVIDIA RTX 4090 D: NVIDIA GeForce RTX 4090

  # RTX 4060Ti 16G: NVIDIA GeForce RTX 4060 Ti
  NVIDIA GEFORCE GTX 16GB: NVIDIA GeForce RTX 4060 Ti
  NVIDIA GeForce GTX 16GB: NVIDIA GeForce RTX 4060 Ti
  RTX 4060Ti 16G: NVIDIA GeForce RTX 4060 Ti
  NVIDIA RTX 4060: NVIDIA GeForce RTX 4060 Ti

  # NVIDIA Tesla T4 variants
  High-RAM T4: NVIDIA Tesla T4
  Cloud T4: NVIDIA Tesla T4
  GPU T4 14.8GB: NVIDIA Tesla T4

  # NVIDIA A100 variants
  DGX A100: NVIDIA A100
  40GB GPU: NVIDIA A100
  GPU 40GB: NVIDIA A100
  Nvidia A180: NVIDIA A100
  NVIDIA A100: NVIDIA A100
  Nvidia DGX A100 20GB: NVIDIA A100
  A100 Nvidia 40GB: NVIDIA A100
  NVIDIA A100 MiG 20GB: NVIDIA A100
  NC96ads-A100: NVIDIA A100
  NVIDIA RTX A100: NVIDIA A100
  Nvidia Ampere A100: NVIDIA A100
  Nvidia Titan A100: NVIDIA A100
  Ampere-architecture GPU A100: NVIDIA A100
  A100 40: NVIDIA A100
  A100: NVIDIA A100
  A100 40GB: NVIDIA A100
  A100 40G: NVIDIA A100
  A100 40Gb: NVIDIA A100
  A100 30GB: NVIDIA A100
  Nvidia A100 40GB: NVIDIA A100
  Nvidia A100 40G: NVIDIA A100
  NVIDIA A100 40GB: NVIDIA A100
  NVIDIA A100 40G: NVIDIA A100
  Nvidia RTX A100: NVIDIA A100
  RTX A100 40GB: NVIDIA A100
  NVIDIA GeForce RTX A100: NVIDIA A100
  DGXA-100: NVIDIA A100

  # NVIDIA A100 PCIe variants
  A100-PCIE-40GB Nvidia GPU: NVIDIA A100 PCIe
  Tesla A100-PCIE-40GB: NVIDIA A100 PCIe
  NVIDIA A100-PCIE 40GB: NVIDIA A100 PCIe
  A100 PCIE 40GB: NVIDIA A100 PCIe
  NVIDIA A100 PCIE 40GB: NVIDIA A100 PCIe
  DGX A100 40GB: NVIDIA A100 PCIe
  A100 PCIE 40GB: NVIDIA A100 PCIe
  A100 PCIe 40: NVIDIA A100 PCIe
  A100 40GB PCIe: NVIDIA A100 PCIe
  A100 40G PCIe: NVIDIA A100 PCIe
  NVIDIA A100-PCIE-40GB: NVIDIA A100 PCIe
  NVIDIA A100-PCIE40GB: NVIDIA A100 PCIe
  A100 PCIe: NVIDIA A100 PCIe
  A100-PCIE-40GB: NVIDIA A100 PCIe
  A100-PCIE 40GB: NVIDIA A100 PCIe
  NVIDIA TESLA A100-PCIE-40GB: NVIDIA A100 PCIe
  Tesla A100 PCIe 40GB: NVIDIA A100 PCIe
  A100 PCIe 40GB: NVIDIA A100 PCIe 

  # NVIDIA A100 80GB variants
  GPU 80GB: NVIDIA A100 PCIe 80GB
  GPU 80G: NVIDIA A100 PCIe 80GB
  DGX A100 80GB: NVIDIA A100 PCIe 80GB
  80GB: NVIDIA A100 PCIe 80GB
  NVIDIA GPU 80GB: NVIDIA A100 PCIe 80GB
  A100 80B: NVIDIA A100 PCIe 80GB
  A100L 80GB: NVIDIA A100 PCIe 80GB
  Ampere A100 80GB: NVIDIA A100 PCIe 80GB
  GPU Nvidia A100-80GB: NVIDIA A100 PCIe 80GB
  NVIDIA Ampere A100 64GB: NVIDIA A100 PCIe 80GB
  NVIDIA Ampere GPU A100 64GB: NVIDIA A100 PCIe 80GB
  custom A100 64GB: NVIDIA A100 PCIe 80GB
  A100 80GB: NVIDIA A100 PCIe 80GB
  A100 80G: NVIDIA A100 PCIe 80GB
  A100 65Gb: NVIDIA A100 PCIe 80GB
  Nvidia A100 80GB: NVIDIA A100 PCIe 80GB
  Nvidia A100 80G: NVIDIA A100 PCIe 80GB
  NVIDIA A100 80GB: NVIDIA A100 PCIe 80GB
  NVIDIA A100 80G: NVIDIA A100 PCIe 80GB
  NVIDIA DGX A100 80GB: NVIDIA A100 PCIe 80GB

  # NVIDIA A100 SXM4 80GB variants
  NVIDIA Tesla A100 SMX4 80GB: NVIDIA A100 SXM4 80 GB
  NVIDIA A100-SXM80GB: NVIDIA A100 SXM4 80 GB
  A100 80GB SXM4: NVIDIA A100 SXM4 80 GB
  NVIDIA SXM4 80GB: NVIDIA A100 SXM4 80 GB
  
  # NVIDIA A100 SXM4 40GB variants
  A100 40GB SXM4: NVIDIA A100 SXM4 40 GB
  A100 SMX4: NVIDIA A100 SXM4 40 GB

  # NVIDIA P40 variants
  NVIDIA Tesla P40: NVIDIA P40
  NVidia P40 46GB: NVIDIA P40
  NVidia P40 23GB: NVIDIA P40
  NVIDIA Tesla P40: NVIDIA P40
  Nvidia Tesla P40 24G: NVIDIA P40
  Tesla P40: NVIDIA P40
  Google CoLab P40: NVIDIA P40
  NVIDIA P40: NVIDIA P40
  Tesla P40 24GB: NVIDIA P40

  # NVIDIA A40 PCIe variants
  GPU 48GB: NVIDIA A40 PCIe
  48G-memory GPU: NVIDIA A40 PCIe
  NVIDIA RTX A40 60GB: NVIDIA A40 PCIe
  NVIDIA RTX A40 48GB: NVIDIA A40 PCIe
  48 GB GPU: NVIDIA A40 PCIe
  NVIDIA A40: NVIDIA A40 PCIe
  A400: NVIDIA A40 PCIe
  A40 40GB: NVIDIA A40 PCIe
  A40 48GB: NVIDIA A40 PCIe
  NVIDIA Ampere A40 48GB: NVIDIA A40 PCIe
  A40 46GB: NVIDIA A40 PCIe
  NVIDIA A40 40GB: NVIDIA A40 PCIe
  NVIDIA A40 48GB PCIe 4.0: NVIDIA A40 PCIe
  Ampere-architecture GPU A40: NVIDIA A40 PCIe
  NVIDIA RTX A40: NVIDIA A40 PCIe
  Nvidia A40 46GB: NVIDIA A40 PCIe
  NVIDIA GTX A40: NVIDIA A40 PCIe
  Tesla A40 40GB: NVIDIA A40 PCIe
  Nvidia GPU A40: NVIDIA A40 PCIe
  Nvidia A40 46068MB: NVIDIA A40 PCIe
  NVIDIA A40 46068MiB: NVIDIA A40 PCIe

  # NVIDIA GeForce RTX 3090
  RTX 3090 24576 MiB: NVIDIA GeForce RTX 3090
  Ampere RTX 3090: NVIDIA GeForce RTX 3090
  NVIDIA GeForce RTX 3039: NVIDIA GeForce RTX 3090
  MSI GeForce RTX 3090: NVIDIA GeForce RTX 3090
  NVIDIA 3O9O 24GB: NVIDIA GeForce RTX 3090
  Nvidia Ge-Force RTX-3090 24G: NVIDIA GeForce RTX 3090
  NVIDIA 3090 GTX: NVIDIA GeForce RTX 3090
  NVIDIA ReForce RTX 3090: NVIDIA GeForce RTX 3090
  NVIDIA GeForce RTX 3090 24576 MiB: NVIDIA GeForce RTX 3090

  # NVIDIA HGX H20 variants
  NVIDIA H20 SXM 96GB: NVIDIA HGX H20
  H2O GPU: NVIDIA HGX H20
  H20 80GB: NVIDIA HGX H20
  NVIDIA HGX H20: NVIDIA HGX H20
  NVIDIA HGX H20 96GB: NVIDIA HGX H20
  NVIDIA HGX H20 96G: NVIDIA HGX H20
  H20 96GB: NVIDIA HGX H20
  H20 GPU: NVIDIA HGX H20
  H20: NVIDIA HGX H20
  NVIDIA HGX H20 96GB: NVIDIA HGX H20
  NVIDIA HGX H20 SXM 96GB: NVIDIA HGX H20
  96G H20: NVIDIA HGX H20
  NVIDIA H20-NVLink 96GB: NVIDIA HGX H20

  # H100 80GB variants
  GPU 120GB: NVIDIA H100 PCIe
  NVIDIA H100 80GB HBM3: NVIDIA H100 PCIe
  H100 80GB PCIe: NVIDIA H100 PCIe
  H100 80GB SXM: NVIDIA H100 SXM5 80 GB
  H100 80GB HBM3: NVIDIA H100 PCIe
  NVIDIA H100 HBM3 80GB: NVIDIA H100 PCIe
  NVIDIA H100 Hopper 96GB HBM2e: NVIDIA H100 PCIe
  NVIDIA H100-80GB-HBM3: NVIDIA H100 PCIe

  # NVIDIA GeForce GTX 1080 variants
  consumer GPU 12GB: NVIDIA GeForce GTX 1080
  Nvidia GeForce 12GB: NVIDIA GeForce GTX 1080
  12GB GPU: NVIDIA GeForce GTX 1080
  GPU 12GB: NVIDIA GeForce GTX 1080
  NVIDIA GeForce GTX 1660 SUPER 6GB: NVIDIA GeForce GTX 1080
  Nvidia GTX 1080X: NVIDIA GeForce GTX 1080
  GeForce GTX 1080 NVIDIA 12GB: NVIDIA GeForce GTX 1080
  11G 1080Ti: NVIDIA GeForce GTX 1080 Ti

  # NVIDIA L20 PCle variants
  NVIDIA L2O: NVIDIA L20 PCle
  NVIDIA L20Y: NVIDIA L20 PCle

  # NVIDIA GeForce RTX 4070 Ti variants
  NVDIA RTX 4070 Ti 12GB: NVIDIA GeForce RTX 4070 Ti
  NVIDIA GeForce RTX 4070 Laptop 8GB: NVIDIA GeForce RTX 4070 Ti

  # NVIDIA GeForce RTX 2080 variants
  8GB GPU: NVIDIA GeForce RTX 2080
  GPU 8GB: NVIDIA GeForce RTX 2080
  
  # NVIDIA GeForce RTX 2080 ti variants
  2080T: NVIDIA GeForce RTX 2080 Ti
  Nvidia 11GB: NVIDIA GeForce RTX 2080 Ti
  GeForce RTX 2080 Titan: NVIDIA GeForce RTX 2080 Ti
  Titan RTX RTX 2080 TI: NVIDIA GeForce RTX 2080 Ti
  NVIDIA Titan 2080Ti: NVIDIA GeForce RTX 2080 Ti
  NVIDIA Titan 2080: NVIDIA GeForce RTX 2080
  Nvidia GTX2020 11G: NVIDIA GeForce RTX 2080 Ti
  NVIDIA GTX 11GB: NVIDIA GeForce RTX 2080 Ti
  Turing RTX 2080Ti: NVIDIA GeForce RTX 2080 Ti
  Nvidia GTX2020 11GB: NVIDIA GeForce RTX 2080 Ti
  NVIDIA GeForce RTX 2080 Ti 11264MiB: NVIDIA GeForce RTX 2080 Ti

  # NVIDIA GeForce RTX 2080 SUPER variants
  NVIDIA RTX2080 SUPER 8GB: NVIDIA GeForce RTX 2080 SUPER
  RTX2080S: NVIDIA GeForce RTX 2080 SUPER
  RTX 2080 Super 8GB: NVIDIA GeForce RTX 2080 SUPER

  # NVIDIA RTX A6000 variants
  RTXA600: NVIDIA RTX A6000
  NVIDIA Tesla A6000: NVIDIA RTX A6000
  NVIDIA GeForce GTS A6000 49GB: NVIDIA RTX A6000
  RXT A6000: NVIDIA RTX A6000
  Tesla A6000: NVIDIA RTX A6000
  NVIDIA A6000 1015: NVIDIA RTX A6000
  Tesla A6000 48GB: NVIDIA RTX A6000
  Quadro RTX A6000 48GB: NVIDIA RTX A6000
  NVIDIA A60 48GB: NVIDIA RTX A6000
  NVIDIA Quadro RTX A6000: NVIDIA RTX A6000
  A6400: NVIDIA RTX A6000
  A6000 GPU 48GB: NVIDIA RTX A6000
  NVIDIA RTXA600 48GB: NVIDIA RTX A6000
  A6000 8GB: NVIDIA RTX A6000

  # NVIDIA RTX 6000 Ada Generation variants
  NVIDIA RTX A6000 Ada: NVIDIA RTX 6000 Ada Generation
  A6000 Ada: NVIDIA RTX 6000 Ada Generation
  A6000 Ada 49GB: NVIDIA RTX 6000 Ada Generation

  # NVIDIA RTX 6000 variants
  RTX 6000 NVIDIA GPU 48GB: NVIDIA Quadro RTX 6000
  GeForce RTX 6000: NVIDIA Quadro RTX 6000
  NVIDIA GeForce RTX 6000 24G: NVIDIA Quadro RTX 6000

  # NVIDIA GeForce RTX 3060 Ti variants
  3060 Ti GPU 8G VRAM: NVIDIA GeForce RTX 3060 Ti
  NVIDIA 3060Ti 8GB: NVIDIA GeForce RTX 3060 Ti

  # NVIDIA GeForce RTX 3050 variants
  RTX 3050 4GB: NVIDIA GeForce RTX 3050

  # uawei Ascend 910B variants
  Ascend 910B4 32GB: Huawei Ascend 910B4
  Ascend 910B3 64GB: Huawei Ascend 910B3
  Ascend 910B NPU 64GB: Huawei Ascend 910B
  Huawei 910B x86 NPU: Huawei Ascend 910B
  NPU 64G: Huawei Ascend 910B

  # NVIDIA GeForce RTX 2060 variants
  Nvidia RTX 2060 Super 8Gb: NVIDIA GeForce RTX 2060 SUPER
  Nvidia RTX 2060 Super 8GB: NVIDIA GeForce RTX 2060 SUPER
  GeForce RTX 2060: NVIDIA GeForce RTX 2060 SUPER
  GeForce RTX 2060 8GB: NVIDIA GeForce RTX 2060 SUPER
  
  # NVIDIA HGX H20O variants
  NVIDIA HGX H20O: NNVIDIA H200 PCIe
  NVIDIA H20O: NVIDIA H200 PCIe
  NVIDIA H20O: NVIDIA H200 PCIe

  # NVIDIA A800 PCIe 40 GB
  NVIDIA RTX A8000: NVIDIA A800 PCIe 40 GB
  NVIDIA A800: NVIDIA A800 PCIe 40 GB

  # NVIDIA A800 PCIe 80 GB
  A800 81920 MiB: NVIDIA A800 PCIe 80 GB
  NVIDIA A8000 80GB: NVIDIA A800 PCIe 80 GB
  A80O: NVIDIA A800 PCIe 80 GB
  NVIDIA RTX A800 80G: NVIDIA A800 PCIe 80 GB
  NVIDIA A80O: NVIDIA A800 PCIe 80 GB
  NVIDIA A80O 80GB: NVIDIA A800 PCIe 80 GB
  NVIDIA A80O 80G: NVIDIA A800 PCIe 80 GB
  NVIDIA RTX A800O: NVIDIA A800 PCIe 80 GB

  
  
  
  NVIDIA GeForce GTX Titan X 11MiB: NVIDIA GeForce GTX TITAN X
  GTX Titan X Pascal 12GB: NVIDIA GeForce GTX TITAN X
  GeForce GTX Titan XP: NVIDIA TITAN Xp
  Nvidia TITAN Xp GPU: NVIDIA TITAN Xp
  NVIDIA GeForce GTX Titan Xp: NVIDIA TITAN Xp
  Titan Xp P8: NVIDIA TITAN Xp
  NVIDIA GP102 TITAN Xp 12GB: NVIDIA TITAN Xp
  Titan RX: NVIDIA TITAN RTX
  GTX Titan: NVIDIA GeForce GTX TITAN
  
  
  
  AWS EC2 p3dn.24xlarge GPU: AWS EC2 p3dn.24xlarge
  Quadro RTX A5000: NVIDIA RTX A5000

  NVIDIA Jetson Nano Orin 8GB: NVIDIA Jetson Orin Nano 8GB
  NVIDIA Jetson Orin Nano: NVIDIA Jetson Orin Nano 8GB
  
  GM204GL: NVIDIA Quadro M4000
  nVidia Quadro P5000 16GB: NVIDIA Quadro P5000
  
  
  
  Nvidia 1060 6GB: NVIDIA GeForce GTX 1060
  
  NVIDIA RTX 3070: NVIDIA GeForce RTX 3070
  
  AWS p3.2xlarge: AWS EC2 p3.2xlarge
  p3.8xlarge: AWS EC2 p3.8xlarge
  GeForce 960: NVIDIA GeForce GTX 960
  p3.16xlarge: AWS EC2 p3.16xlarge
  p3dn.24xlarge: AWS EC2 p3dn.24xlarge
  DGX-2H: NVIDIA DGX-2H
  DGX-1V: NVIDIA DGX-1V
  
  
  
  
  NVIDIA H800: NVIDIA H800 PCIe
  Tesla H800 80GB: NVIDIA H800 PCIe
  g5.4xlarge GPU: AWS EC2 g5.4xlarge
  NVIDIA H800 80GB: NVIDIA H800 PCIe
  NVIDIA H80O 80GB: NVIDIA H800 PCIe
  NVIDIA H80O: NVIDIA H800 PCIe
  NVIDIA H8oo: NVIDIA H800 PCIe
  H8Oo GPU: NVIDIA H800 PCIe
  Nvidia GeForce RTX 2070 8GB: NVIDIA GeForce RTX 2070
  
  A5500 24GB: NVIDIA RTX A5500
  
  NVIDIA Tesla L4 24GB: NVIDIA L4
  Quadro P6000 24GB: NVIDIA Quadro P6000
  
  
  
  
  TPU: Google TPU v3
  p3.8xlarge AWS EC2 instance: AWS EC2 p3.8xlarge
  AMD Instinct MI250X: AMD Radeon Instinct MI250X
  MI250X: AMD Radeon Instinct MI250X
  
  NVIDIA GeForce GTX 1650 4GB: NVIDIA GeForce GTX 1650
  Google research TPU v4: Google TPU v4
  v3-32 TPU pod: Google TPU v3
  v3-8 TPUs: Google TPU v3
  multi-host TPU: Google TPU v3
  eight-core TPU: Google TPU v3
  
  Tensor Processing Unit: Google TPU v3
  Google Tensor Processing Unit (TPU): Google TPU v3
  Tensor Processing Units (TPUs): Google TPU v3
  Google research TPU: Google TPU v3
  H800 80G: NVIDIA H800 PCIe
  MI250x: AMD Radeon Instinct MI250X
  
  
  
  
  NVIDIA RTX 4500: NVIDIA RTX A4500
  
  g5.12xlarge AWS instance: AWS EC2 g5.12xlarge
  AMD-MI200 64GB: AMD Instinct MI210


  
  
  
  
  
  Nvidia Pascal P100: NVIDIA Tesla P100 PCIe 16GB
  
  

  
  
  
  2nd generation TPU: Google TPU v2
  Cloud TPU Pod: Google TPU v3
  
  
  GeForce GTX 1060 6GB: NVIDIA GeForce GTX 1060
  
  
  RTX 8000 NVIDIA GPU 48GB: NVIDIA Quadro RTX 8000

  
  


  

  
  
  
  NVIDIA L4OS: NVIDIA L40S
  L4OS GPU: NVIDIA L40S
  GH2OO: NVIDIA GH200
  NVIDIA GH2OO: NVIDIA GH200
  
  
  MI30oX: AMD Instinct MI300X
  
  L4 GPU 24G VRAM: NVIDIA L4
  
  
  NVIDIA GTX1050 Mobile 4GB: NVIDIA GeForce GTX 1050
  
  
  
  
  
  
  AWS p4de.24xlarge: AWS EC2 p4de.24xlarge
  Nvidia P4: NVIDIA Tesla P4
  
  NVIDIA Quadro P100: NVIDIA P100
  
  Google TPU: Google TPU v3
  
  NVidia Pascal-100: NVIDIA Tesla P100 PCIe 16GB

  
  Google Cloud v3-8 TPU: Google TPU v3
  
  
  Google v3-8 Cloud TPUs: Google TPU v3
  TPU pod: Google TPU v3
  

  
  NVIDIA Quadro RTX 5000 16GB: NVIDIA Quadro RTX 5000
  Cloud TPU V3 Pod: Google TPU v3
  Titan P100: NVIDIA Tesla P100 PCIe 16GB
  

  
  Cloud TPU v3 Pod: Google TPU v3
  
  Tesla P100 16280 MiB: NVIDIA Tesla P100 PCIe 16GB
  Kepler K80: NVIDIA Tesla K80
  Quadra RTX 8000: NVIDIA Quadro RTX 8000

  
  
  
  GE-MX110 2GB: NVIDIA GeForce MX110
  GeForce MX110 2GB: NVIDIA GeForce MX110

  
  Quradro RTX 8000: NVIDIA Quadro RTX 8000
  
  NVIDIA-SMI Quadro RTX 8000: NVIDIA Quadro RTX 8000
  GCP-TPUv3: Google TPU v3
  GCP-TPUv4: Google TPU v4

  
  Google TPU v2-8: Google TPU v2
  
  TPUv3 128GB: Google TPU v3
  Quadro RTX 4000 16GB: NVIDIA Quadro RTX 4000
  Google Cloud TPU v3.8: Google TPU v3

  
  
  AMD Radeon Pro WX 9100 16GB: AMD Radeon Pro WX 9100
  
  
  GCP TPUv4: Google TPU v4

  Nvidia DGX-2 Station: NVIDIA DGX-2

  
  
  
  
  
  
  
  
  



